#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
    path: /
    controller: App\Controller\HomeController::index

login:
    path: login
    controller: App\Controller\UserController::index

app_logout:
    path: /logout
    methods: GET

###movies:
###    path: /movie
###    controller: App\Controller\ApiController::ApiConnect
