#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
    path: /
    controller: App\Controller\HomeController::index

###movies:
###    path: /movie
###    controller: App\Controller\ApiController::ApiConnect
